const fs = require('fs');
const content = fs.readFileSync('src/lib/translations.ts', 'utf8');

// The ja block is corrupt from line ~2500 to ~3300.
// Let's find it by regex and replace it with a clean structure.
// I will use a simple one for now that follows the interface but has "Japanese" text.
const jaBlockTemplate = `ja: {
    common: {
        settings: '設定',
        download: 'ダウンロード',
        processing: '処理中...',
        apply: '適用',
        cancel: 'キャンセル',
        error: 'エラー',
        success: '成功',
        selectImage: '画像を選択',
        dropHere: 'ここにドロップ',
        orClick: 'またはクリックして選択',
        shareResult: '結果を共有',
        copiedLink: 'リンクをコピーしました',
        trySample: 'サンプルを試す',
        copyImage: '画像をコピー',
        imageCopied: '画像がクリップボードにコピーされました',
        imageCopyError: '画像のコピーに失敗しました'
    },
    navbar: {
        title: 'UltraUtils',
        home: 'ホーム',
        imageSuite: '画像エディタ',
        promptGen: 'AIプロンプト',
        ytGrab: 'YTサムネイル',
        qrGen: 'QR生成',
        textConv: 'テキスト変換',
        bgRemover: '背景削除',
        ytPlanner: 'YouTube企画',
        pdfMaster: 'PDF Meister',
        imageRestorer: '画像復元'
    },
    imageRestorer: {
        title: 'AI 写真復元',
        desc: 'AIを使用して古い写真を即座に復元します。'
    },
    imageMaster: {
        title: '画像マスター',
        desc: '高度な最適化と編集ツール。',
        quality: '品質',
        size: 'サイズ',
        width: '幅',
        height: '高さ',
        smartEnhance: 'スマート補正',
        smartEnhanceDesc: 'AIによる画質改善',
        original: 'オリジナル',
        optimized: '最適化済み',
        saveMsg: '保存されました',
        applyOptimize: '最適化を適用',
        downloadOptimized: '最適化された画像を保存',
        guide: {
            title: '画像マスターガイド',
            subtitle: 'プロのように画像を最適化する方法',
            sections: [
                { title: '1. 圧縮と品質のバランス', content: 'UltraUtilsは画質を損なうことなくファイルサイズを削減します。' }
            ],
            faq: [
                { q: '無料ですか？', a: 'はい、完全に無料です。' }
            ]
        }
    },
    promptGen: {
        title: 'AIプロンプト生成器',
        desc: 'Suno、Midjourneyなどに最適なプロンプトを作成。',
        platform: 'プラットフォーム',
        genre: 'ジャンル',
        subject: '主題',
        subjectPlaceholder: '何についてですか？',
        details: '詳細',
        detailsPlaceholder: 'スタイル、光、楽器など...',
        outputTitle: '生成されたプロンプト',
        copy: 'コピー',
        copied: 'コピー済み!',
        placeholder: 'ここに出力されます...',
        platforms: {
            midjourney: 'Midjourney',
            suno: 'Suno AI',
            stableDiffusion: 'Stable Diffusion'
        },
        genres: { cinematic: 'シネマティック', anime: 'アニメ', realistic: 'リアル' },
        guide: {
            title: 'プロンプトガイド',
            subtitle: 'AIの可能性を最大限に引き出す',
            sections: [ { title: '1. 具体的に書く', content: '詳細な記述がより良い結果を生みます。' } ],
            faq: [ { q: '何回生成できますか？', a: '無制限です。' } ]
        }
    },
    ytGrab: {
        title: 'YouTubeサムネイル',
        desc: '高解像度のサムネイルを簡単に取得して編集。',
        placeholder: 'YouTubeのURLを貼り付け',
        getBtn: 'サムネイルを取得',
        invalidUrl: '無効なURLです',
        fetching: '取得中...',
        downloadHd: 'HDをダウンロード',
        editBtn: 'IAで編集 (背景削除)',
        simulatorTitle: 'YouTubeフィード体験',
        simulatorSubtitle: 'プレビュー',
        simulatorDesc: '公開前にどのように見えるか確認。',
        safeZoneBtn: 'セーフゾーン',
        shortsSafeZoneBtn: 'Shortsセーフゾーン',
        colorPalette: 'カラーパレット',
        closeBtn: '閉じる',
        guide: {
            title: 'サムネイル活用ガイド',
            subtitle: 'クリック率(CTR)を最大値にする',
            sections: [ { title: '1. 視認性を高める', content: '主要な被写体を強調。' } ],
            faq: [ { q: '解像度は？', a: '最高品質で取得します。' } ]
        }
    },
    qrGen: {
        title: 'プロフェッショナルQR',
        desc: 'カスタムロゴ付きのQRコードを生成。',
        target: 'URL / テキスト',
        fgColor: '前景',
        bgColor: '背景',
        size: 'サイズ',
        downloadPng: 'PNG保存',
        downloadSvg: 'SVG保存',
        vectorReady: 'ベクター準備完了',
        uploadLogo: 'ロゴをアップロード',
        logoSize: 'ロゴサイズ',
        removeLogo: 'ロゴを削除',
        templates: 'テンプレート',
        styles: 'スタイル',
        frames: 'フレーム',
        frameText: 'フレームテキスト',
        presets: { instagram: 'IG', youtube: 'YT', link: 'Link', wifi: 'WiFi' },
        guide: {
            title: 'QRマスターガイド',
            subtitle: 'ブランドを表現するQRコード',
            sections: [ { title: '1. 読み取りテスト', content: 'コントラストを明確に保つ。' } ],
            faq: [ { q: '商用利用は？', a: '完全に無料です。' } ]
        }
    },
    textConverter: {
        title: 'テキスト変換',
        desc: '大文字、小文字、並べ替え、クリーニング。',
        inputPlaceholder: 'ここにテキストを貼り付け',
        statsCharacters: '文字数',
        statsWords: '単語数',
        statsLines: '行数',
        categoryCase: '大文字/小文字',
        categoryCleanup: 'クリーニング',
        categoryWeb: 'ウェブ/エンコード',
        categoryData: 'データ整理',
        btnUppercase: '大文字',
        btnLowercase: '小文字',
        btnCapitalize: '先頭大文字',
        btnTrim: '空白削除',
        btnRemoveEmpty: '空行削除',
        btnRemoveDupes: '重複行削除',
        btnRemoveDupesWords: '重複語削除',
        btnUrlEncode: 'URLエンコード',
        btnUrlDecode: 'URLデコード',
        btnBase64Encode: 'Base64化',
        btnBase64Decode: 'Base64戻し',
        btnJsonFormat: 'JSON整形',
        btnSortAz: '昇順',
        btnSortZa: '降順',
        btnCopy: 'コピー',
        btnCopied: 'コピー済み',
        btnClear: 'クリア',
        guide: {
            title: 'テキストマスターガイド',
            subtitle: '作業を効率化する',
            sections: [ { title: '1. 一括処理', content: '何千行ものデータを一瞬で処理。' } ],
            faq: [ { q: 'データは保存されますか？', a: 'ローカルで処理されるため、送信されません。' } ]
        }
    },
    bgRemover: {
        title: '背景削除 PRO',
        desc: 'AIによる瞬時の背景削除と編集。',
        preparing: '準備中...',
        processing: '処理中...',
        modelLoading: 'AIモデル読み込み中...',
        downloadReady: '準備完了',
        dropMsg: 'ここに画像をドロップ',
        comparison: '前後比較',
        stepFetch: '読み込み',
        stepModel: 'AI準備',
        stepInference: '抽出中',
        refineTitle: '手動修正',
        refineDesc: 'ディテールを仕上げる。',
        brushRestore: '復元',
        brushErase: '削除',
        brushSize: 'サイズ',
        applyRefine: '適用',
        cancelRefine: 'キャンセル',
        stickerEffect: 'ステッカー',
        stickerColor: '枠色',
        backgroundColor: '背景色',
        bgTransparent: '透過',
        bgSolid: '塗りつ불',
        bgGradient: 'グラデーション',
        bgImage: '画像背景',
        undo: '元に戻す',
        redo: 'やり直し',
        reset: 'リセット',
        zoom: 'ズーム',
        idPhoto: '証明写真',
        passport: 'パスポート',
        usVisa: 'ビザ',
        idCard: '身分証',
        bgLibrary: '背景ライブラリ',
        uploadCustomBg: '背景アップロード',
        addText: '文字追加',
        deleteText: '文字削除',
        deleteImage: '削除',
        resetPos: '位置リセット',
        subjectScale: '被写体サイズ',
        brightness: '明るさ',
        contrast: 'コントラスト',
        saturation: '彩度',
        rotation: '回転',
        flipH: '左右反転',
        flipV: '上下反転',
        opacity: '透明度',
        shadow: '影',
        tabTransform: '変形',
        tabEnhance: '補正',
        tabStyling: '加工',
        alignment: '整列',
        centerH: '中央(横)',
        centerV: '中央(縦)',
        bringToFront: '前面へ',
        sendToBack: '背面へ',
        filterPresets: 'フィルタ',
        filterOriginal: 'オリジナル',
        filterBW: '白黒',
        filterSepia: 'セピア',
        filterWarm: 'ウォーム',
        filterCool: 'クール',
        filterVintage: 'ビンテージ',
        textEditing: '文字編集',
        textPlaceholder: 'ここに入力',
        textSize: '文字サイズ',
        stickerWidth: '枠幅',
        shortsCrop: 'Shorts切り抜き',
        share: '共有',
        shareText: 'AIで背景を削除しました!',
        photoMode: 'モード選択',
        studio: 'スタジオ',
        original: '元画像',
        result: '結果',
        compare: '比較',
        scale: '縮尺',
        bgTrsp: '透過',
        bgClr: 'カラー',
        bgGrad: 'グラデ',
        bgImg: '画像',
        scaleLabel: '拡大/縮小',
        resetConfirmTitle: 'リセットしますか？',
        resetConfirmDesc: 'すべての変更が失われます。',
        aspectTitle: 'アスペクト比',
        aspectSquare: '正方形',
        aspectSocial: 'SNS',
        aspectTV: 'HD',
        edgeTitle: '境界線の調整',
        edgeDesc: 'より自然な切り抜き。',
        precisionTitle: '精密加工',
        precisionDesc: '1px単位の修正。',
        proBgTitle: 'プロ背景',
        proBgDesc: 'スタジオ品質の合成。',
        guide: {
            title: '背景削除マスターガイド',
            subtitle: '完璧な透過画像を作成。',
            sections: [ { title: '1. 明確な境界線', content: 'コントラストがはっきりした画像が最適。' } ],
            faq: [ { q: '無料ですか？', a: 'はい、完全に無料です。' } ]
        }
    },
    pdfMaster: {
        title: 'PDF Meister PRO',
        desc: '究極のPDFキット。結合、分割、変換、保護を簡単に。',
        merge: '結合',
        split: '分割',
        toImage: '画像へ変換',
        rotate: '回転',
        protect: 'パスワード設定',
        uploadMsg: 'PDFをドロップまたはクリック',
        filesSelected: '個のファイルを選択済み',
        mergeNow: '結合PDF作成',
        splitNow: '全ページ分割',
        rotateNow: '90\u00b0回転適用',
        protectNow: '暗号化',
        downloadMerged: '結果をダウンロード',
        downloadSplit: 'ZIPで保存',
        addMore: '追加',
        clear: 'クリア',
        pageRange: 'ページ範囲 (例: 1-5)',
        password: 'パスワード入力',
        options: '詳細設定',
        processingMsg: 'PDF処理中...',
        successMsg: '完了しました!',
        guide: {
            title: 'PDF活用ガイド',
            subtitle: 'プロのように管理',
            sections: [ { title: '1. 安全な暗号化', content: 'ブラウザ内で処理されるため安心。' } ],
            faq: [ { q: 'サイズ制限は？', a: '100MB以下を推奨します。' } ]
        }
    },
    home: {
        badge: '完全無料 & プライバシー優先',
        titlePrefix: '現代のクリエイターへ',
        titleSuffix: 'デジタルの超能力を',
        desc: '厳選された高性能ユーティリティツールのコレクション。',
        descLine2: '登録不要、課金なし、純粋な機能美。',
        launchTool: 'ツールを起動',
        missionTitle: 'プライバシー重視の高性能ユーティリティ',
        missionDesc1: 'UltraUtilsへようこそ。100%無料、完全ローカル、そしてプロフェッショナルな設計。',
        missionDesc2: 'AI背景削除からSEO最適化まで、ファイルをサーバーにアップロードすることなくブラウザ内で処理します。',
        features: {
            privacy: { title: 'プライバシー', desc: 'サーバーアップなし' },
            speed: { title: 'スピード', desc: 'ローカル高速処理' },
            global: { title: 'グローバル', desc: '多言語対応' },
            free: { title: '無料', desc: '隠し費用なし' }
        },
        footerNote: {
            title: 'すべての人のためのプロツール',
            subtitle: 'UltraUtilsが信頼される理由。',
            media: { title: 'メディアスイート', desc: '動画・画像のクリエイティブフロー。' },
            data: { title: 'データとテキスト', desc: 'アナリスト必携の変換ツール。' },
            design: { title: 'デザイン', desc: '高品質なQRコードとブランディング。' }
        },
        growthTips: {
            title: 'デジタルの成長ヒント',
            subtitle: 'アクセスアップのためのエキスパートチップ。',
            tips: [
                { title: 'YouTube CTR戦略', desc: '競合のサムネイルを分析し改善。', tool: 'YT Grabber', href: '/tools/youtube-thumbnail' }
            ]
        },
        nextStep: '次のステップへ',
        suggestNext: 'おすすめ'
    },
    advertise: {
        title: '広告掲載',
        desc: 'UltraUtilsであなたのブランドを宣伝。',
        benefit1: 'グローバルリーチ',
        benefit2: '高い信頼性',
        benefit3: '柔軟なプラン',
        faq: [ { q: '掲載期間は？', a: '最短1週間から可能です。' } ]
    },
    footer: {
        tools: 'ツール一覧',
        company: 'サービス',
        social: 'SNS',
        desc: '現代のクリエイターのためのデジタルの超能力ツールキット。',
        allTools: 'すべてのツール',
        privacy: 'プライバシーポリシー',
        terms: '利用規約',
        about: '私たちについて',
        contact: 'お問い合わせ'
    },
    privacy: { title: 'プライバシーポリシー', desc: 'プライバシーを最優先。' },
    terms: { title: '利用規約' },
    about: { title: 'UltraUtilsについて', desc: '最高級の無料ツールを提供。' },
    contact: { title: 'お問い合わせ', desc: 'ご質問はこちらから。' },
    notFound: { title: '404 - 見つかりません', desc: 'ページが存在しないか移動しました。' },
    feedback: { title: 'フィードバック', placeholder: 'ご意見をお聞かせください...' },
    share: { title: '共有', desc: '友達に教える' },
    ytPlanner: {
        title: 'YouTube企画マスター',
        desc: 'AIがバイラルタイトルや構成案を生成。',
        setupTitle: '企画設定',
        topic: '動画のトピック',
        topicPlaceholder: '例) 痩せるレシピ, 旅行Vlog...',
        vibe: '雰囲気',
        vibeGeneral: '一般',
        vibeExpert: '専門的',
        targetAudience: '視聴者ターゲット',
        targetGeneral: '一般層',
        targetExpert: '専門家',
        targetBeginner: '初心者',
        resultsTitle: 'AI分析レポート',
        setupTab: '設定',
        resultsTab: 'レポート',
        copyAll: 'すべてコピー',
        copied: 'コピーしました!',
        guide: {
            title: 'YT成功ガイド',
            subtitle: 'アルゴリズムを味方に',
            sections: [ { title: '1. CTRの心理学', content: 'クリックを誘発するタイトルの作り方。' } ],
            faq: [ { q: 'AIタイトルはそのまま使えますか？', a: 'はい、最適化されていますがアレンジも可能です。' } ]
        }
    },
    houseAds: { bgRemoverTitle: '背景削除PRO', bgRemoverDesc: 'AI精度を体感。', imageRestorerTitle: '写真復元AI', imageRestorerDesc: '古い写真をHDに。', pdfMasterTitle: 'PDFエディタ', pdfMasterDesc: '結合・分割を簡単に。', imageCompTitle: '画像圧縮', imageCompDesc: '高品質で容量削減。', ytGrabTitle: 'サムネイルHD', ytGrabDesc: '瞬時に取得。', coffeeTitle: 'コーヒーを奢る', coffeeDesc: '開発の励みになります！' }
},`;

const newContent = content.replace(/ja: \{[\s\S]*?es: \{/, jaBlockTemplate + '\n    es: {');
fs.writeFileSync('src/lib/translations.ts', newContent);
console.log('Successfully fully restored and fixed ja block in translations.ts');
