'use client'

import { useState, useEffect, useMemo, useRef } from 'react'
import { Wand2, Sparkles, Zap, Copy, Check, Video, MessageSquare, Lightbulb, ChevronRight, Terminal, Sliders, Download } from 'lucide-react'
import { cn } from '@/lib/utils'
import { useLanguage } from '@/context/language-context'
import AdBanner from '@/components/AdBanner'
import { addRecentTool } from '@/lib/recent-tools'
import NextStep from '@/components/NextStep'

export default function YoutubePlannerClient() {
    const { t } = useLanguage()
    const [isMounted, setIsMounted] = useState(false)
    const [videoType, setVideoType] = useState('vlog')
    const [topic, setTopic] = useState('')
    const [tone, setTone] = useState('funny')
    const [target, setTarget] = useState('general')
    const [isGenerating, setIsGenerating] = useState(false)
    const [showResults, setShowResults] = useState(false)
    const [activeTab, setActiveTab] = useState('titles')
    const [mobileView, setMobileView] = useState<'setup' | 'results'>('setup')
    const [copied, setCopied] = useState<boolean | 'all'>(false)
    const toolRef = useRef<HTMLDivElement>(null)

    useEffect(() => {
        setIsMounted(true)
        addRecentTool({
            id: 'yt-planner',
            title: t.navbar.ytPlanner,
            href: '/tools/youtube-planner',
            iconName: 'Wand2'
        })
    }, [t])

    const handleGenerate = () => {
        if (!topic) return
        setIsGenerating(true)
        setShowResults(false)

        // Simulate AI processing
        setTimeout(() => {
            setIsGenerating(false)
            setShowResults(true)
            // Auto switch to results on mobile
            setMobileView('results')

            // Precision Scroll: Scroll directly to the tool container start
            if (window.innerWidth < 1024 && toolRef.current) {
                const offset = toolRef.current.offsetTop - 80;
                window.scrollTo({ top: offset, behavior: 'smooth' });
            }
        }, 1500)
    }

    const handleCopy = (text: string) => {
        navigator.clipboard.writeText(text)
        setCopied(text === 'all' ? 'all' : true)
        setTimeout(() => setCopied(false), 2000)
    }

    const handleDownload = () => {
        if (!generatedContent) return
        const content = `
[ ${t.ytPlanner.title} - ${topic} ]
-----------------------------------------
1. ${t.ytPlanner.tabTitles}
${generatedContent.titles.join('\n')}

2. ${t.ytPlanner.tabTags}
${generatedContent.tags}

3. ${t.ytPlanner.tabScripts}
${generatedContent.script}

4. ${t.ytPlanner.tabStrategy}
${generatedContent.strategy}
-----------------------------------------
Generated by UltraUtils AI
        `
        const blob = new Blob([content], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `yt_plan_${topic.replace(/\s+/g, '_')}.txt`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
    }

    // --- Dynamic AI Simulation Logic ---
    const generatedContent = useMemo(() => {
        if (!topic) return null;

        const titlePatterns = {
            vlog: {
                funny: [
                    `🤣 ${topic} 하다가 진짜 배꼽 빠질 뻔...`,
                    `현실판 ${topic}! 브이로그 찍다 멘붕 온 사연`,
                    `누가 ${topic}을 이렇게 해요? ㅋㅋㅋ (feat. 병맛)`,
                    `절대 따라하지 마세요... ${topic} 대실패 브이로그`,
                    `${topic} 하러 갔다가 의문의 똥참기 챌린지 됨`,
                    `아니.. ${topic}이 이렇게 웃긴 거였음? ㅋㅋㅋ`,
                    `${topic} 브이로그 찍는데 뒤에서 친구가 춤추고 있음`,
                    `초딩도 안 하는 ${topic} 실수, 제가 해냈습니다`,
                    `${topic} 하다가 경찰 올 뻔한 썰 푼다.. 😂`,
                    `인생이 시트콤인 사람의 ${topic} 일상 브이로그`
                ],
                serious: [
                    `진솔하게 담아본 ${topic}의 기록`,
                    `나의 소중한 일상, 그리고 ${topic}...`,
                    `내가 ${topic}을 계속하는 이유 (솔직한 심정)`,
                    `마음이 편해지는 ${topic} 힐링 브이로그`,
                    `번아웃 끝에 마주한 ${topic}, 그리고 깨달음`,
                    `누구에게도 말하지 못한 ${topic}에 대한 고민`,
                    `조용히 혼자 즐기는 ${topic} 일기`,
                    `내일을 위한 오늘의 ${topic} 기록`,
                    `${topic}을 통해 배운 삶의 태도`,
                    `평범한 일상이 ${topic}으로 특별해지는 과정`
                ],
                professional: [
                    `프로 크리에이터의 ${topic} 라이프 스타일`,
                    `${topic}과 함께하는 생산적인 하루 루틴`,
                    `고퀄리티 일상 영상: ${topic} 편`,
                    `효율적인 ${topic}을 위한 브이로그 장비 세팅`,
                    `직업이 ${topic}인 사람의 흔한 출근 루틴`,
                    `${topic} 전문가의 브이로그는 무엇이 다를까?`,
                    `일상 속 ${topic}을 예술로 만드는 편집 꿀팁`,
                    `${topic} 컨텐츠를 위한 장소 섭외 및 촬영 비하인드`,
                    `워커홀릭의 ${topic} 브이로그 (feat. 갓생 살기)`,
                    `고퀄리티 브이로그의 정석: ${topic} 촬영 노하우`
                ]
            },
            info: {
                funny: [
                    `빡치기 전에 꼭 봐야할 ${topic} 완벽 가이드`,
                    `잼민이도 이해하는 ${topic} 초간단 정리`,
                    `${topic} 하다가 빡쳐서 만든 영상 (핵깔끔)`,
                    `이거 모르면 ${topic} 하다가 호구 됩니다 ㅋㅋ`,
                    `${topic} 전문가라고 자부하던 친구의 처참한 최후`,
                    `당신이 알던 ${topic}은 다 가짜입니다 (충격주의)`,
                    `${topic} 3분 요약 안 보면 오늘 잠 안 옴`,
                    `뇌 빼고 봐도 이해되는 ${topic} 개론`,
                    `엄마도 물어보는 ${topic}, 이 영상 하나로 종결`,
                    `${topic} 때문에 밤새 본 사람? 이거 보고 자러 가셈`
                ],
                serious: [
                    `${topic}의 숨겨진 위기, 우리가 몰랐던 진실`,
                    `학술적으로 접근한 ${topic}의 기원과 미래`,
                    `${topic}, 과연 이대로 괜찮은가? (심층 분석)`,
                    `심도 깊은 통찰: ${topic}에 대한 모든 리포트`,
                    `역사를 바꾼 ${topic}, 그 이면의 이야기들`,
                    `${topic}이 우리 사회에 미치는 영향 (PD 수첩 톤)`,
                    `전문가가 본 ${topic} 시장의 장기 전망`,
                    `누구도 가르쳐주지 않는 ${topic}의 본질`,
                    `${topic}의 실체: 과연 무엇이 진실일까?`,
                    `기술적 분석: ${topic}의 팩트와 루머`
                ],
                professional: [
                    `[전문가 가이드] ${topic} 완벽 마스터하기`,
                    `${topic} 실전 전략: 상위 1%만 아는 노하우`,
                    `비즈니스 관점에서의 ${topic} 활용법`,
                    `${topic} 입문부터 심화까지! 1시간 압축 강의`,
                    `프로를 위한 ${topic} 고급 활용 테크닉`,
                    `${topic} 시장에서 성공하는 확실한 로드맵`,
                    `업계 1위가 제안하는 ${topic} 프로젝트 관리법`,
                    `${topic} 데이터 분석을 통한 트렌드 예측`,
                    `성공적인 ${topic} 포트폴리오를 만드는 법`,
                    `컨설턴트가 공개하는 ${topic} 효율 극대화 비법`
                ]
            },
            review: {
                funny: [
                    `돈 지랄인가? ${topic} 직접 써보니... 😂`,
                    `광고 아님! ${topic} 내돈내산 솔직 리뷰 (욕 주의)`,
                    `대기업이 싫어할 ${topic} 단점 팩트 폭격`,
                    `${topic}? 그냥 이거 사지 마세요 ㅋㅋㅋ`,
                    `${topic} 리뷰하다가 물건 던질 뻔한 사연`,
                    `이걸 왜 이제 샀지? ${topic} 개꿀템 발견!`,
                    `${topic} 리뷰계의 이단아 등장 (솔직함 200%)`,
                    `친구한테 욕 먹고 추천하는 ${topic} 리뷰`,
                    `싼 게 비지떡? ${topic} 가성비 테스트`,
                    `이거 만든 사람 누구냐? ${topic} 황당 리뷰`
                ],
                serious: [
                    `${topic} 한 달 사용기: 과연 기대만큼일까?`,
                    `객관적으로 비교한 ${topic} vs 경쟁 모델`,
                    `전문가가 평가한 ${topic}의 내구성 테스트`,
                    `${topic}, 장점보다 단점이 더 치명적인 이유`,
                    `${topic} 구매 전 필수 시청! (후회 예방)`,
                    `실사용자 100명이 말하는 ${topic}의 리얼 후기`,
                    `${topic}의 디테일한 리뷰: 끝판왕 등장`,
                    `가격 그 이상의 가치? ${topic} 심층 리뷰`,
                    `${topic} 하드웨어 및 소프트웨어 총평`,
                    `장기간 사용 후 본 ${topic}의 민낯`
                ],
                professional: [
                    `산업 표준 점검: ${topic} 벤치마크 테스트`,
                    `엔지니어 입장에서 본 ${topic}의 기술적 구조`,
                    `B2B 리뷰: 기업용으로 본 ${topic}의 가치`,
                    `${topic} 심층 분석: 성능과 가성비의 균형점`,
                    `테크 유튜버가 추천하는 최고 사양 ${topic}`,
                    `국내 최초 ${topic} 언박싱 및 성능 평가`,
                    `${topic} 공식 명세서 분석 및 실제 성능 비교`,
                    `워크플로우 최적화를 위한 ${topic} 도입 가이드`,
                    `생산성 향상을 위한 ${topic} 필수 점검 리스트`,
                    `비즈니스 효율을 높여주는 ${topic} 솔직 리뷰`
                ]
            },
            shorts: {
                funny: [
                    `${topic} 1초 만에 하는 법 ㅋㅋㅋ`,
                    `흔한 한국인의 ${topic} 속도... 미쳤음`,
                    `절대 끝까지 보지마세요... ${topic} 반전`,
                    `진짜 ${topic} 끝판왕 등장 ㄷㄷ`,
                    `${topic} 하다가 현타 온 순간 🤣`,
                    `너만 모르는 ${topic} 개꿀팁`,
                    `${topic} 실패 영상 (웃음 참기 힘듦)`,
                    `친구 몰래 ${topic} 해주기 몰카 ㅋㅋㅋ`,
                    `이 영상 보면 ${topic} 하고 싶어짐`,
                    `세상에서 가장 빠른 ${topic} 챌린지`
                ],
                serious: [
                    `60초 안에 배우는 ${topic}의 핵심`,
                    `아무도 몰랐던 ${topic}의 소름돋는 사실`,
                    `당신이 놓치고 있는 ${topic} 꿀팁`,
                    `단 30초, ${topic}이 인생을 바꿀 수 있다면?`,
                    `${topic}의 위력: 15초면 충분합니다`,
                    `이거 본 후로 ${topic}이 달라졌어요`,
                    `${topic} 입문자를 위한 필수 쇼츠`,
                    `30초 정리: ${topic}에 대한 오해와 진실`,
                    `${topic} 핵심 요약본 (저장 필수)`,
                    `당신의 시간을 아껴줄 ${topic} 가이드`
                ],
                professional: [
                    `프로가 알려주는 ${topic} 숏폼 공식`,
                    `${topic} 효율 200% 높이는 방법`,
                    `Shorts 전략: ${topic} 알고리즘 타는 법`,
                    `바쁜 현대인을 위한 ${topic} 60초 요약`,
                    `성공적인 ${topic} 쇼츠 제작 기술`,
                    `${topic} 쇼츠 조회수 떡상하는 치트키`,
                    `15초의 미학: ${topic}으로 시청자 사로잡기`,
                    `${topic} 전문가의 숏폼 루틴 대공개`,
                    `${topic} 숏폼으로 퍼스널 브랜딩 하기`,
                    `기업용 쇼츠 기획: ${topic} 활용 백서`
                ]
            }
        };

        const currentType = titlePatterns[videoType as keyof typeof titlePatterns] || titlePatterns.vlog;
        const currentTone = currentType[tone as keyof typeof currentType] || currentType.professional;

        // More advanced deterministic selection for variety
        const topicHash = Array.from(topic).reduce((acc, char) => acc + char.charCodeAt(0), 0);
        const startIndex = topicHash % Math.max(1, currentTone.length - 4);
        const selectedTitles = currentTone.slice(startIndex, startIndex + 5);

        const tagBases = ['YouTube', 'Creator', 'Tip', 'Trend', 'Viral', 'Motivation', 'Hacks', 'Korea', 'Global'];
        const selectedBases = tagBases.sort(() => 0.5 - (topicHash % 10 / 10)).slice(0, 5);
        const dynamicTags = [topic, ...selectedBases.map(b => topic + b), 'UltraUtils'].map(t => `#${t.replace(/\s+/g, '')}`).join(' ');

        const scriptIntros = {
            beginner: `안녕하세요! 오늘은 '${topic}'에 아예 처음 입문하시는 분들을 위해 기초부터 탄탄하게, 하나하나 짚어드릴게요. 어렵게만 느껴졌던 '${topic}', 이 영상 하나면 끝납니다!`,
            general: `반갑습니다! 요즘 어디를 가나 '${topic}' 이야기가 빠지질 않죠? 과연 왜 이렇게 화제인지, 그리고 우리가 주목해야 할 포인트는 무엇인지 지금 바로 알아봅시다!`,
            expert: `반갑습니다. 오늘은 '${topic}' 분야에서 한 단계 더 나아가고자 하는 분들을 위해 고난도 테크닉과 현직 전문가들만 아는 실무 인사이트를 심층적으로 다뤄보겠습니다.`
        };

        const currentIntro = scriptIntros[target as keyof typeof scriptIntros] || scriptIntros.general;

        const thumbnailPatterns = [
            `😱 ${topic} 진짜 실화? (충격)`,
            `사장님 몰래 찍은 ${topic} 비결`,
            `인생 필수템 ${topic} (안 사면 후회)`,
            `${topic} 1분 컷! (초간단)`,
            `절대 따라하지 마세요.. ${topic} 경고`,
            `1%만 아는 ${topic}의 비밀 대공개`,
            `이것만 알면 당신도 ${topic} 고수`,
            `진짜 ${topic} 끝판왕을 찾았습니다`,
            `내 돈 다 날린 ${topic} 솔직 후기`,
            `누구나 할 수 있는 ${topic} (꿀팁)`
        ];
        const selectedThumbnailText = thumbnailPatterns.sort(() => 0.5 - (topicHash % 7 / 7)).slice(0, 4);

        const strategyPatterns = {
            vlog: `📍 ${topic} 브이로그 노출 전략:\n1. 썸네일 포인트: 자연스러운 일상 컷과 상반되는 자극적인 텍스트 조합 제안.\n2. 제목에 '썰/후기/몰랐던' 단어를 포함하여 클릭률 유도.\n3. 고정 댓글을 통해 시청자와 소통하고 '다음 편'에 대한 기대감 심어주기.\n4. 시청 대상 [${target}]의 활동 시간에 맞춰 업로드 권장.`,
            info: `📍 ${topic} 정보전달 노출 전략:\n1. 썸네일 포인트: 깔끔한 배경색과 고해상도 텍스트로 '신뢰감' 형성.\n2. 핵심 키워드를 제목 앞부분에 배치하여 검색 노출(SEO) 최적화.\n3. 영상 설명란에 타임스탬프를 제공하여 시청 지속 시간 향상.\n4. 관련 있는 대형 채널의 댓글창을 참고하여 타겟팅 키워드 발굴.`,
            review: `📍 ${topic} 제품 리뷰 노출 전략:\n1. 썸네일 포인트: 제품의 클로즈업 샷과 '감정(표정)'이 드러나는 연출.\n2. 제목에 구체적인 가격이나 '돈 값 하는가?' 등의 질문형 문구 배치.\n3. 영상 초반 5초 내에 '이 제품의 가장 치명적인 단점'을 언급하여 이탈 방지.\n4. 설명란에 제휴 링크 및 상세 스펙을 정리하여 정보성 강화.`,
            shorts: `📍 ${topic} 숏폼 노출 전략:\n1. 썸네일 포인트: 가장 역동적인 순간이나 결과물을 단 0.1초 만에 보여주기.\n2. 첫 3초 안에 시선을 끌지 못하면 패배! 무조건 강렬한 사운드와 자막으로 시작.\n3. 끝까지 보지 않으면 알 수 없는 '반전' 요소를 배치하여 루프 유도.\n4. 해시태그에 트렌드 키워드와 컨셉(#${topic})을 적절히 혼합.`
        };

        const currentStrategy = strategyPatterns[videoType as keyof typeof strategyPatterns] || strategyPatterns.vlog;

        return {
            titles: selectedTitles,
            tags: dynamicTags,
            thumbnailText: selectedThumbnailText,
            script: `[인트로: 20초]\n${currentIntro}\n\n[본론: 4~8분]\n1. ${topic}을 대하는 올바른 자세 (마인드셋)\n2. ${tone === 'funny' ? '포복절도' : tone === 'professional' ? '체계적인' : '진정성 있는'} 실전 활용 사례 3가지\n3. ${target === 'beginner' ? '초보자가 가장 많이 하는 실수 TOP 5' : '상위 1%만 아는 숨겨진 꿀팁'} 대공개\n4. 실제 사용자들이 궁금해하는 ${topic} Q&A 세션\n\n[아웃트로: 40초]\n오늘 영상이 도움되셨다면 구독과 좋아요 부탁드려요! '${topic}'에 대해 더 궁금한 점이 있다면 댓글 남겨주세요. 다음 영상에서 만나요!`,
            strategy: currentStrategy
        };
    }, [topic, videoType, tone, target]);

    if (!isMounted) return null

    const videoTypes = [
        { id: 'vlog', label: t.ytPlanner.vlog, icon: Video },
        { id: 'info', label: t.ytPlanner.info, icon: Lightbulb },
        { id: 'review', label: t.ytPlanner.review, icon: Sparkles },
        { id: 'shorts', label: t.ytPlanner.shorts, icon: Zap }
    ]

    return (
        <div className="max-w-7xl mx-auto space-y-12 pb-20">
            {/* Header Section */}
            <div className="text-center space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-amber-500/10 text-amber-600 dark:text-amber-400 text-xs font-bold uppercase tracking-widest border border-amber-500/20">
                    <Sparkles className="w-4 h-4" /> Creator Studio
                </div>
                <h1 className="text-4xl font-extrabold tracking-tight sm:text-6xl">
                    <span className="text-gradient from-amber-500 to-rose-500 font-black">{t.ytPlanner.title}</span>
                </h1>
                <p className="text-muted-foreground text-lg max-w-2xl mx-auto leading-relaxed">
                    {t.ytPlanner.desc}
                </p>
            </div>

            {/* Top Ad Slot */}
            <div className="max-w-4xl mx-auto px-4">
                <AdBanner slot="top-banner-planner" />
            </div>

            <div ref={toolRef} className="space-y-8">
                {/* Mobile View Toggle */}
                <div className="lg:hidden sticky top-16 z-40 flex bg-white/95 dark:bg-zinc-950/95 backdrop-blur-md p-1.5 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xl mx-4">
                    <button
                        onClick={() => setMobileView('setup')}
                        className={cn(
                            "flex-1 py-3 rounded-xl text-sm font-black transition-all flex items-center justify-center gap-2",
                            mobileView === 'setup' ? "bg-amber-500 text-white shadow-md" : "text-zinc-500"
                        )}
                    >
                        <Sliders className="w-4 h-4" /> {t.ytPlanner.setupTab}
                    </button>
                    <button
                        onClick={() => setMobileView('results')}
                        className={cn(
                            "flex-1 py-3 rounded-xl text-sm font-black transition-all flex items-center justify-center gap-2",
                            mobileView === 'results' ? "bg-amber-500 text-white shadow-md" : "text-zinc-500"
                        )}
                    >
                        <Terminal className="w-4 h-4" /> {t.ytPlanner.resultsTab}
                        {showResults && <span className="w-2 h-2 rounded-full bg-rose-500 animate-pulse" />}
                    </button>
                </div>

                <div className="grid lg:grid-cols-2 gap-12 items-start px-4">
                    {/* Left Side: Inputs */}
                    <div className={cn(
                        "glass-card p-6 sm:p-10 rounded-[2.5rem] sm:rounded-[3rem] space-y-8 sm:space-y-10 animate-in fade-in slide-in-from-left-8 duration-700 delay-200",
                        mobileView !== 'setup' && "hidden lg:block"
                    )}>
                        <div className="space-y-6">
                            <label className="text-sm font-bold flex items-center gap-2 uppercase tracking-widest text-muted-foreground italic">
                                1. {t.ytPlanner.videoType}
                            </label>
                            <div className="grid grid-cols-2 gap-3">
                                {videoTypes.map((type) => (
                                    <button
                                        key={type.id}
                                        onClick={() => setVideoType(type.id)}
                                        className={cn(
                                            "relative group flex items-center justify-center gap-3 py-5 px-6 rounded-2xl font-bold transition-all overflow-hidden",
                                            videoType === type.id
                                                ? "bg-amber-500 text-white shadow-xl scale-[1.02]"
                                                : "bg-zinc-100 dark:bg-zinc-800 text-muted-foreground hover:bg-zinc-200 dark:hover:bg-zinc-700"
                                        )}
                                    >
                                        <type.icon className={cn("w-5 h-5", videoType === type.id ? "animate-pulse" : "group-hover:scale-110 transition-transform")} />
                                        <span>{type.label}</span>
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div className="space-y-6">
                            <label className="text-sm font-bold flex items-center gap-2 uppercase tracking-widest text-muted-foreground italic lg:mt-6">
                                2. {t.ytPlanner.topic}
                            </label>
                            <div className="relative group">
                                <input
                                    value={topic}
                                    onChange={(e) => setTopic(e.target.value)}
                                    placeholder={t.ytPlanner.topicPlaceholder}
                                    className="w-full pl-8 pr-16 py-6 rounded-3xl bg-zinc-100 dark:bg-zinc-800 border-2 border-transparent focus:border-amber-500/30 focus:ring-4 focus:ring-amber-500/10 text-xl font-medium transition-all outline-none"
                                />
                                <div className="absolute right-6 top-1/2 -translate-y-1/2 text-muted-foreground opacity-50 group-focus-within:text-amber-500 group-focus-within:opacity-100 transition-all pointer-events-none">
                                    <MessageSquare className="w-6 h-6" />
                                </div>
                            </div>
                        </div>

                        <div className="pt-6 border-t border-zinc-100 dark:border-zinc-800 space-y-8">
                            <div className="space-y-4">
                                <label className="text-xs font-black uppercase tracking-widest text-muted-foreground/60">{t.ytPlanner.advancedOptions}</label>
                                <div className="grid grid-cols-2 gap-8">
                                    <div className="space-y-4">
                                        <span className="text-sm font-bold block">{t.ytPlanner.tone}</span>
                                        <select
                                            value={tone}
                                            onChange={(e) => setTone(e.target.value)}
                                            className="w-full px-4 py-3 rounded-xl bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-sm font-medium outline-none focus:ring-2 focus:ring-amber-500/20 transition-all"
                                        >
                                            <option value="funny">{t.ytPlanner.toneFunny}</option>
                                            <option value="serious">{t.ytPlanner.toneSerious}</option>
                                            <option value="professional">{t.ytPlanner.toneProfessional}</option>
                                        </select>
                                    </div>
                                    <div className="space-y-4">
                                        <span className="text-sm font-bold block">{t.ytPlanner.targetAudience}</span>
                                        <select
                                            value={target}
                                            onChange={(e) => setTarget(e.target.value)}
                                            className="w-full px-4 py-3 rounded-xl bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-sm font-medium outline-none focus:ring-2 focus:ring-amber-500/20 transition-all"
                                        >
                                            <option value="general">{t.ytPlanner.targetGeneral}</option>
                                            <option value="expert">{t.ytPlanner.targetExpert}</option>
                                            <option value="beginner">{t.ytPlanner.targetBeginner}</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <button
                                onClick={handleGenerate}
                                disabled={!topic || isGenerating}
                                className={cn(
                                    "w-full py-6 rounded-[2rem] font-black text-2xl flex items-center justify-center gap-4 transition-all shadow-2xl relative overflow-hidden group",
                                    topic && !isGenerating
                                        ? "bg-gradient-to-r from-amber-500 via-rose-500 to-amber-500 bg-[length:200%_auto] hover:bg-right hover:scale-[1.02] active:scale-95 text-white"
                                        : "bg-zinc-200 dark:bg-zinc-800 text-muted-foreground cursor-not-allowed"
                                )}
                            >
                                {isGenerating ? (
                                    <>
                                        <Wand2 className="w-8 h-8 animate-spin" />
                                        <span>{t.ytPlanner.generating}</span>
                                    </>
                                ) : (
                                    <>
                                        <Zap className="w-8 h-8 group-hover:animate-bounce" />
                                        <span>{t.ytPlanner.generateBtn}</span>
                                    </>
                                )}
                            </button>
                        </div>
                    </div>

                    {/* Right Side: Results */}
                    <div className={cn(
                        "space-y-8 animate-in fade-in slide-in-from-right-8 duration-700 delay-300",
                        mobileView !== 'results' && "hidden lg:block"
                    )}>
                        <div className="overflow-hidden rounded-[2.5rem] sm:rounded-[3rem] shadow-2xl bg-zinc-950 border border-white/10 flex flex-col min-h-[500px] sm:min-h-[640px]">
                            {/* Fake Browser Header */}
                            <div className="bg-zinc-900 p-6 flex items-center justify-between border-b border-white/5 h-20">
                                <div className="flex gap-2">
                                    <div className="w-3 h-3 rounded-full bg-rose-500/40" />
                                    <div className="w-3 h-3 rounded-full bg-amber-500/40" />
                                    <div className="w-3 h-3 rounded-full bg-emerald-500/40" />
                                </div>
                                <div className="flex bg-zinc-800/50 p-1 rounded-xl">
                                    {['titles', 'scripts', 'tags', 'strategy'].map((tab) => (
                                        <button
                                            key={tab}
                                            onClick={() => setActiveTab(tab)}
                                            className={cn(
                                                "px-4 py-1.5 rounded-lg text-xs font-black transition-all",
                                                activeTab === tab
                                                    ? "bg-amber-500 text-white shadow-lg"
                                                    : "text-zinc-500 hover:text-zinc-300"
                                            )}
                                        >
                                            {t.ytPlanner[tab === 'titles' ? 'tabTitles' : tab === 'scripts' ? 'tabScripts' : tab === 'tags' ? 'tabTags' : 'tabStrategy']}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            {/* Content Area */}
                            <div className="flex-1 p-10 font-mono relative overflow-y-auto max-h-[500px] scrollbar-hide">
                                {!showResults ? (
                                    <div className="h-full flex flex-col items-center justify-center text-center space-y-6 opacity-40">
                                        <Terminal className="w-16 h-16" />
                                        <p className="font-mono text-sm uppercase tracking-widest">Waiting for creative input...</p>
                                    </div>
                                ) : (
                                    <div className="animate-in fade-in slide-in-from-bottom-5 duration-500">
                                        <div className="text-amber-500 text-sm mb-6 flex items-center gap-2 select-none">
                                            <ChevronRight className="w-4 h-4" />
                                            <span className="text-zinc-600">~/projects/viral-video</span>
                                            <span className="text-zinc-400">$ plan --output {activeTab}</span>
                                        </div>

                                        <div className="space-y-6">
                                            {activeTab === 'titles' && (
                                                <>
                                                    {generatedContent?.titles.map((title: string, i: number) => (
                                                        <div key={i} className="group relative p-4 rounded-2xl bg-white/5 border border-white/5 hover:border-amber-500/30 transition-all font-sans">
                                                            <p className="text-white text-lg leading-relaxed">{title}</p>
                                                            <button
                                                                onClick={() => handleCopy(title)}
                                                                className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 p-2 text-amber-500 transition-all bg-zinc-900 rounded-lg shadow-xl"
                                                            >
                                                                <Copy className="w-4 h-4" />
                                                            </button>
                                                        </div>
                                                    ))}
                                                    <div className="mt-8 pt-8 border-t border-white/10 space-y-4 font-sans">
                                                        <span className="text-xs font-black text-rose-500 uppercase tracking-widest italic flex items-center gap-2">
                                                            <Sparkles className="w-4 h-4" /> Thumbnail Hook Recommendation
                                                        </span>
                                                        <div className="grid grid-cols-2 gap-3">
                                                            {generatedContent?.thumbnailText.map((text: string, i: number) => (
                                                                <div key={i} className="p-3 bg-rose-500/10 border border-rose-500/20 rounded-xl text-white text-sm font-bold text-center">
                                                                    {text}
                                                                </div>
                                                            ))}
                                                        </div>
                                                    </div>
                                                </>
                                            )}

                                            {activeTab === 'tags' && (
                                                <div className="p-6 rounded-2xl bg-white/5 border border-white/5 font-sans">
                                                    <p className="text-amber-400 text-xl tracking-wide leading-loose">{generatedContent?.tags}</p>
                                                </div>
                                            )}

                                            {activeTab === 'scripts' && (
                                                <div className="p-6 rounded-2xl bg-white/5 border border-white/5 whitespace-pre-wrap font-sans text-white/90 leading-relaxed text-lg">
                                                    {generatedContent?.script}
                                                </div>
                                            )}

                                            {activeTab === 'strategy' && (
                                                <div className="p-6 rounded-2xl bg-white/5 border border-white/5 whitespace-pre-wrap font-sans text-emerald-400 leading-relaxed text-lg">
                                                    {generatedContent?.strategy}
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* Footer Copy All Button */}
                            <div className="p-8 bg-zinc-900/50 border-t border-white/5 mt-auto space-y-3">
                                <button
                                    onClick={() => handleCopy(
                                        activeTab === 'titles' ? (generatedContent?.titles.join('\n') || '') :
                                            activeTab === 'tags' ? (generatedContent?.tags || '') :
                                                activeTab === 'scripts' ? (generatedContent?.script || '') :
                                                    (generatedContent?.strategy || '')
                                    )}
                                    disabled={!showResults}
                                    className={cn(
                                        "w-full py-5 rounded-2xl font-black text-lg flex items-center justify-center gap-3 transition-all",
                                        !showResults ? "bg-zinc-800 text-zinc-500 cursor-not-allowed" :
                                            copied ? "bg-emerald-600 text-white" : "bg-white text-zinc-950 hover:bg-zinc-200"
                                    )}
                                >
                                    {copied ? <><Check className="w-6 h-6" /> {t.ytPlanner.copied}</> : <><Copy className="w-6 h-6" /> {t.ytPlanner.copyAll}</>}
                                </button>
                                <div className="grid grid-cols-2 gap-3">
                                    <button
                                        onClick={handleDownload}
                                        disabled={!showResults}
                                        className={cn(
                                            "w-full py-4 rounded-2xl font-bold text-base flex items-center justify-center gap-2 transition-all bg-zinc-800 text-zinc-300 hover:bg-zinc-700",
                                            !showResults && "opacity-50 cursor-not-allowed"
                                        )}
                                    >
                                        <Download className="w-5 h-5" /> .TXT
                                    </button>
                                    <button
                                        onClick={async () => {
                                            await navigator.clipboard.writeText(window.location.href);
                                            alert(t.common.copiedLink);
                                        }}
                                        disabled={!showResults}
                                        className={cn(
                                            "w-full py-4 rounded-2xl font-bold text-base flex items-center justify-center gap-2 transition-all bg-zinc-800 text-zinc-300 hover:bg-zinc-700",
                                            !showResults && "opacity-50 cursor-not-allowed"
                                        )}
                                    >
                                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" /></svg>
                                        Share Tool
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Bottom Ad Slot */}
            <div className="max-w-4xl mx-auto px-4 mt-12">
                <AdBanner slot="bottom-banner-planner" />
            </div>

            {/* Guide Section */}
            <div className="mt-24 space-y-16 animate-in fade-in slide-in-from-bottom-8 duration-1000 delay-500 px-4">
                <div className="text-center space-y-4">
                    <h2 className="text-3xl font-black sm:text-4xl">{t.ytPlanner.guide.title}</h2>
                    <p className="text-muted-foreground">{t.ytPlanner.guide.subtitle}</p>
                </div>

                <div className="grid md:grid-cols-3 gap-8">
                    {t.ytPlanner.guide.sections.map((section: { title: string; content: string }, i: number) => (
                        <div key={i} className="glass-card p-8 rounded-[2.5rem] space-y-4 hover:shadow-xl transition-shadow border-2 border-amber-500/5">
                            <div className="w-12 h-12 rounded-2xl bg-amber-500/10 flex items-center justify-center text-amber-600 font-black text-xl">
                                {i + 1}
                            </div>
                            <h3 className="text-xl font-bold">{section.title}</h3>
                            <p className="text-muted-foreground leading-relaxed text-sm">
                                {section.content}
                            </p>
                        </div>
                    ))}
                </div>

                {/* FAQ Section */}
                <div className="max-w-3xl mx-auto space-y-8">
                    <h3 className="text-2xl font-black text-center mb-10">자주 묻는 질문 (FAQ)</h3>
                    <div className="grid gap-4">
                        {t.ytPlanner.guide.faq.map((item: { q: string; a: string }, i: number) => (
                            <div key={i} className="glass-card p-6 rounded-2xl border border-zinc-100 dark:border-zinc-800">
                                <h4 className="font-bold text-lg mb-2 text-amber-600 dark:text-amber-400">Q. {item.q}</h4>
                                <p className="text-muted-foreground text-sm leading-relaxed">{item.a}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Next Step Suggestion */}
            <NextStep
                title={t.navbar.ytGrab}
                desc={t.ytGrab.desc}
                href="/tools/youtube-thumbnail"
                iconName="Youtube"
            />
        </div>
    )
}
